using UnityEngine;

public class CameraMove : MonoBehaviour
{
    Player player;
    [SerializeField]
    private GameObject BackGround; //”wŒiæ“¾
    private Vector3 FirstPos; //”wŒi‚ÌÅ‰‚ÌˆÊ’u‚ğæ“¾
    void Start()
    {
        player = FindObjectOfType<Player>();
        FirstPos = BackGround.transform.position;
    }

    // Update is called once per frame
    void Update()
    {
        if (player.transform.position.x < 0)
        {
            transform.position = new Vector3(0, transform.position.y, -10); //XÀ•W‚ª0ˆÈ‰º‚È‚çƒJƒƒ‰‚ğˆÚ“®‚³‚¹‚È‚¢
        }
        else
        {
            transform.position = new Vector3(player.transform.position.x, transform.position.y, -10); //ƒJƒƒ‰‚ğƒvƒŒƒCƒ„[‚É’Ç]‚³‚¹‚é
        }
        BackGround.transform.position = (transform.position / 1.5f) + FirstPos; //”wŒi‚É“®‚«‚ğ—^‚¦‚é
    }
}
